### PR TITLE
Azure pipelines and a test

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
🎉 also fixes the dependency problem.

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
@Windos you'll have to create the Azure Pipelines instance or give me more repo permissions

**Comment by TylerLeonhardt** [comment]
@Windos + @steviecoaster ping :)

**Comment by Windos** [comment]
Sorry! Yeah lol looks good. Not sure if I can customize access anymore
unless we move the repo to an org?

**Comment by steviecoaster** [comment]
Me like! Looks good. As far as more access, yeah it probably needs moved to
an organization.

**Comment by TylerLeonhardt** [comment]
@Windos if you don't mind enabling Azure DevOps, we can defer creating on Org for now :) honestly, we could throw all the notification modules in an uber org but that's for another day :)

**Comment by Windos** [comment]
Yeah, I'll get on that tonight (azure, not Uber org lol)

**Comment by TylerLeonhardt** [comment]
Then with that I think we're ready for a 0.1.0 release? 😄

**Comment by Windos** [comment]
Only thing left is a little comment based help (I can put that in)

Passing: https://dev.azure.com/windosnz/PoshNotify/_build/results?buildId=1

**Pull request merged**
